services:
  - type: web
    name: edito
    env: php
    plan: free
    region: frankfurt
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"